apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bases/ambientor.io_clusters.yaml
  - bases/ambientor.io_clusterconnections.yaml
  - bases/ambientor.io_meshinventories.yaml
  - bases/ambientor.io_ambientassessments.yaml
  - bases/ambientor.io_migrationplans.yaml
  - bases/ambientor.io_rollouts.yaml
  - bases/ambientor.io_policytranslations.yaml
